# Generated by Django 3.2.5 on 2021-07-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipoAlimen', models.TextField(verbose_name='Tipo alimento')),
                ('raza', models.TextField(verbose_name='Raza')),
                ('precioReal', models.FloatField(verbose_name='Precio real')),
                ('precioActual', models.FloatField(verbose_name='Precio actual')),
            ],
        ),
        migrations.CreateModel(
            name='Vaca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('peso', models.TextField(verbose_name='Peso')),
                ('raza', models.TextField(default='Vaca', verbose_name='Raza')),
                ('sexo', models.TextField(verbose_name='Sexo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
