# Generated by Django 3.2.5 on 2021-07-08 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacunos', '0002_auto_20210707_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='vaca',
            options={'ordering': ['-created']},
        ),
    ]
